name: WindowPicker
author: patcullen
category: Interface
tags: [animation, UI, transition, CSS3]
#docs: http://pat.cullen.co.za/project/WindowPicker
#demo: http://pat.cullen.co.za/project/WindowPicker/demo
#current: 0.1